#!/bin/bash

remove_images() {

    ################################################
    # Removendo a imagem docker do locacaobike
    ################################################
    
    docker rmi /locacaobike
    
    ################################################
    # Gerando a imagem docker do subscriber
    ################################################
    
    docker rmi /subscriber
    
    ################################################
    # Executando o docker compose (DOWN)
    # --rmi all (remove images)
    ################################################
    
    docker compose down --rmi all
}

while getopts ":r" option; do
   case $option in
      r) # remove images
         remove_images
   esac
done

################################################
# Executando o docker compose (DOWN)
# -v (remove volumes)
################################################

docker compose down -v