apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    run: rabbitmq
spec:
  ports:
    - port: 5672
      name: rabbitmq
    - port: 15672
      name: management
  selector:
    app: rabbitmq
