name: ci-push

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build locacaobike with Maven
        run: mvn -B package --file locacaobike/pom.xml

      - name: Build subscriber with Maven
        run: mvn -B package --file subscriber/pom.xml
      
      - name: Build and push locacaobike image
        uses: docker/build-push-action@v5
        with:
          context: locacaobike
          file: locacaobike/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/locacaobike:latest

      - name: Build and push subscriber image
        uses: docker/build-push-action@v5
        with:
          context: subscriber
          file: subscriber/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/subscriber:latest
